---
-
  hosts: all
  tasks:
    -
      command: "echo {{inventory_hostname}}"
      name: "echo test"
      when: ansible_default_ipv4.address == "192.168.36.177"
      register: iptest
    -
      shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined
    -
      command: echo {{ item }}
      with_items: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
    -
      command: echo test
      name: match register ip
      when: iptest.stdout== "cent2"

    -
      name: debug
      debug: msg="{{iptest.stdout}}"
      when: ansible_default_ipv4.address == "192.168.36.177"
